version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    steps:
      - node/install:
          node-version: "20"
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            cd MyStore && npm install
      - run:
          name: Install API Dependencies
          command: |
            echo "Installing backend dependencies"
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            echo "Building the frontend app"
            cd MyStore && npm run build
      - run:
          name: API Build
          command: |
            echo "Building the backend API"
            npm run start:backend
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "20"
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy App
          command: |
            echo "Installing and building applications"
            npm run backend:install
            cd MyStore && npm install
            cd .. && npm run build:backend
            cd MyStore && npm run build
            echo "Deploying applications to AWS"
workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
