version: 2.1
orbs:
  node: circleci/node@5.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  frontend:
    working_directory: ~/app/MyStore/app/MyStore
    executor: node/default
    steps:
      - checkout:
          path: ~/app/MyStore
      - node/install:
          node-version: "20.11"
      - run:
          name: Install Angular CLI
          command: npm install -g @angular/cli
      - run:
          name: Install Package
          command: npm install
      - run:
          name: Build
          command: npm run build
      - aws-cli/setup
      - run:
          name: Prepare for deployment
          command: |
            mkdir -p ../../dist/frontend
            cp -r dist/my-store/* ../../dist/frontend/

  api:
    working_directory: ~/app/MyStore
    executor: node/default
    steps:
      - checkout:
          path: ~/app/MyStore
      - node/install:
          node-version: "20.11"
      - run:
          name: Install Package
          command: npm install
      - run:
          name: Build Backend
          command: npx tsc -p app/backend/tsconfig.json
      - eb/setup
      - run:
          name: Create deployment files
          command: |
            # Create Procfile
            echo "web: npm start" > Procfile
            
            # Create necessary directories
            mkdir -p .ebextensions
            
            # Create basic configuration
            echo 'option_settings:' > .ebextensions/01_nodecommand.config
            echo '  aws:elasticbeanstalk:container:nodejs:' >> .ebextensions/01_nodecommand.config
            echo '    NodeCommand: "npm start"' >> .ebextensions/01_nodecommand.config
            echo '  aws:elasticbeanstalk:application:environment:' >> .ebextensions/01_nodecommand.config
            echo '    NODE_ENV: production' >> .ebextensions/01_nodecommand.config
            echo '    PORT: 8081' >> .ebextensions/01_nodecommand.config
      - run:
          name: Deploy
          command: |
            # Copy frontend files
            mkdir -p dist/app/MyStore
            cp -r dist/frontend/* dist/app/MyStore/
            
            # Deploy to Elastic Beanstalk
            eb use MyStore-dev
            eb deploy MyStore-dev

workflows:
  mystore:
    jobs:
      - frontend:
          filters:
            branches:
              only:
                - master
      - api:
          requires:
            - frontend
          filters:
            branches:
              only:
                - master