version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: cimg/node:20.19.0
    steps:
      - checkout
      - node/install:
          node-version: '20.19.0'
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      - run:
          name: Install API Dependencies
          command: |
            echo "Installing backend dependencies"
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            echo "Building the frontend app"
            cd MyStore && npm run build
      - run:
          name: API Start
          command: |
            echo "Starting the backend API"
            npm run start:backend & 
            sleep 5
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: '20.19.0'
      - eb/setup
      - aws-cli/setup
      - run:
          name: Deploy App
          command: |
            echo "Installing and building applications"
            npm run backend:install
            npm run frontend:install
            cd MyStore && npm run build
            echo "Deploying applications to AWS"
workflows:
  Mystore:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
